name: build

on:
  push:
    branches:
      - master
      - develop
      - feature-*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make kernel
      run: |
        docker build -f Dockerfile-build -t minosv2_build .
