name: minOSv2 CI

on:
  push:
    branches:
      - master
      - develop
      - feature-*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make kernel
      run: make kernel
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make test
